/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.56
 * Generated at: 2026-06-25 02:13:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class registro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("  <title>SignLearn — Registro</title>\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap\" rel=\"stylesheet\" />\n");
      out.write("  <style>\n");
      out.write("    * { margin: 0; padding: 0; box-sizing: border-box; }\n");
      out.write("    :root {\n");
      out.write("      --azul: #1e40af;\n");
      out.write("      --azul-claro: #3b82f6;\n");
      out.write("      --amarillo: #f0b100;\n");
      out.write("      --texto: #1e293b;\n");
      out.write("      --suave: #64748b;\n");
      out.write("      --fondo: #f8fafc;\n");
      out.write("      --borde: #e2e8f0;\n");
      out.write("    }\n");
      out.write("    body { font-family: \"Inter\", sans-serif; background: var(--fondo); color: var(--texto); min-height: 100vh; display: flex; flex-direction: column; }\n");
      out.write("    header { background: var(--azul); padding: 16px 24px; display: flex; justify-content: space-between; align-items: center; }\n");
      out.write("    .logo { color: white; font-size: 20px; font-weight: 800; }\n");
      out.write("    .badge { color: var(--amarillo); font-size: 12px; font-weight: 600; border: 1px solid var(--amarillo); padding: 4px 12px; border-radius: 20px; }\n");
      out.write("    main { flex: 1; display: flex; align-items: center; justify-content: center; padding: 40px 20px; }\n");
      out.write("    .card { background: white; border-radius: 24px; box-shadow: 0 8px 30px rgba(0,0,0,0.08); padding: 36px; width: 100%; max-width: 480px; }\n");
      out.write("    .card h2 { font-size: 22px; font-weight: 800; text-align: center; color: var(--texto); }\n");
      out.write("    .card p { text-align: center; color: var(--suave); font-size: 14px; margin-top: 6px; margin-bottom: 24px; }\n");
      out.write("    .input-group { margin-bottom: 16px; }\n");
      out.write("    .input-group label { display: block; font-size: 13px; font-weight: 600; margin-bottom: 6px; color: var(--texto); }\n");
      out.write("    .input-group input { width: 100%; padding: 12px 14px; border: 1px solid var(--borde); border-radius: 10px; font-size: 14px; font-family: \"Inter\", sans-serif; outline: none; transition: border-color 0.2s; }\n");
      out.write("    .input-group input:focus { border-color: var(--azul-claro); }\n");
      out.write("    .btn { width: 100%; padding: 14px; background: var(--azul); color: white; border: none; border-radius: 10px; font-size: 15px; font-weight: 700; cursor: pointer; margin-top: 8px; font-family: \"Inter\", sans-serif; transition: background 0.2s; }\n");
      out.write("    .btn:hover { background: #1e3a8a; }\n");
      out.write("    .mensaje { margin-top: 16px; padding: 12px 16px; border-radius: 10px; font-size: 14px; text-align: center; display: none; }\n");
      out.write("    .exito { background: #dcfce7; color: #166534; display: block; }\n");
      out.write("    .error { background: #fee2e2; color: #991b1b; display: block; }\n");
      out.write("    footer { background: var(--texto); padding: 16px; text-align: center; color: rgba(255,255,255,0.6); font-size: 12px; }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <header>\n");
      out.write("    <div class=\"logo\">👋 SignLearn</div>\n");
      out.write("    <span class=\"badge\">Registro de usuarios</span>\n");
      out.write("  </header>\n");
      out.write("  <main>\n");
      out.write("    <div class=\"card\">\n");
      out.write("      <h2>Crear cuenta</h2>\n");
      out.write("      <p>Completa el formulario para registrarte en SignLearn</p>\n");
      out.write("      ");
 if (request.getAttribute("mensaje") != null) { 
      out.write("\n");
      out.write("        <div class=\"mensaje ");
      out.print( (Boolean)request.getAttribute("exito") ? "exito" : "error" );
      out.write("\">\n");
      out.write("          ");
      out.print( request.getAttribute("mensaje") );
      out.write("\n");
      out.write("        </div>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("      <form action=\"registro\" method=\"POST\">\n");
      out.write("        <div class=\"input-group\">\n");
      out.write("          <label>Documento de Identidad</label>\n");
      out.write("          <input type=\"text\" name=\"documento\" placeholder=\"Ej: 1234567890\" required />\n");
      out.write("        </div>\n");
      out.write("        <div class=\"input-group\">\n");
      out.write("          <label>Nombres</label>\n");
      out.write("          <input type=\"text\" name=\"nombres\" placeholder=\"Tus nombres\" required />\n");
      out.write("        </div>\n");
      out.write("        <div class=\"input-group\">\n");
      out.write("          <label>Apellidos</label>\n");
      out.write("          <input type=\"text\" name=\"apellidos\" placeholder=\"Tus apellidos\" required />\n");
      out.write("        </div>\n");
      out.write("        <div class=\"input-group\">\n");
      out.write("          <label>Correo Electrónico</label>\n");
      out.write("          <input type=\"email\" name=\"correo\" placeholder=\"tu@correo.com\" required />\n");
      out.write("        </div>\n");
      out.write("        <div class=\"input-group\">\n");
      out.write("          <label>Teléfono de Contacto</label>\n");
      out.write("          <input type=\"tel\" name=\"telefono\" placeholder=\"Ej: 3001234567\" required />\n");
      out.write("        </div>\n");
      out.write("        <button type=\"submit\" class=\"btn\">Registrarme</button>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("  </main>\n");
      out.write("  <footer>© 2026 SignLearn · Alfred Vásquez · GA7-220501096-AA2-EV01</footer>\n");
      out.write("</body>\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
